os: osx
osx_image: xcode11.5
language: swift
script: 
- xcodebuild clean build test -project ./FeedFetcher/FeedFetcher.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
- xcodebuild clean build test -workspace ./FeedFetchApp/FeedFetchApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" ONLY_ACTIVE_ARCH=YES
